### ISSUE TITLE
A sequence with all identical counts causes a fatal error

### ISSUE THREAD

**Issue by dereksonderegger** [tdhock/coseg#20]
The following will cause a fatal error:

library(PeakSegOptimal)
series <- data.frame(
  count  = as.integer( rep(0, times=100) ),
  chromStart = as.integer(1:100),
  chromEnd   = as.integer(1:100 + 1))

PeakSegFPOPchrom(series, 10)

This is easy enough for the user to work around but a fatal error is never ok.

**Comment by tdhock** [comment]
hi @dereksonderegger thanks for the bug report. I finally got around to fixing this in #21
