### ISSUE TITLE
Regularized isotonic regression solver

### ISSUE THREAD

**Issue by tdhock** [tdhock/coseg#3]
I got the linear time constrained optimal segmentation C++ code working, for the Poisson Loss and the PeakSeg constraint (changes are up, down, up, down, ...).

It should be relatively straightforward to adapt the existing code for the isotonic regression constraint (changes are up, up, up, ...). For the Poisson Loss (non-negative count data) I could write the isotonic regression code pretty much immediately. For other losses it will be more complicated. @guillemr said that he will work on the Normal/square loss in the coming weeks.

@jpvert with what kind of data did you want to use the regularized isotonic regression model? (normal, poisson, ...?) Also, for your code, what parameterization would be better?
- The FPOP/Optimal Partitioning algorithm takes as input a penalty parameter lambda, and returns one model that minimizes the penalized cost. Probably better if you know what lambda penalty parameter that you want to use.
- The PDPA/Segment Neighborhood algorithm takes as input the maximum number of segments S, and returns optimal models with 1, ..., S segments. Probably better if you don't know what penalty or number of segments is best, and you want to try several different models.

**Comment by jpvert** [comment]
@tdhock : For the application I have in mind, we would need to have the normal loss in order to plug it as proximal operator in the https://github.com/jpvert/apg package
For that we would need the FPOP variant that takes lambda as input

**Comment by tdhock** [comment]
hey @jpvert my collaborator @jewellsean is working on the IsotonicFPOP function https://github.com/jewellsean/coseg/blob/master/R/IsotonicFPOP.R which implements the FPOP/Optimal Paritioning model for the normal/square loss and the isotonic regression constraint. Although it is still under active development (there may be some bugs), you can now try and see if his code would work for your application.

**Comment by tdhock** [comment]
closing this issue because reduced isotonic regression is now implemented in https://github.com/vrunge/gfpop
